### ISSUE TITLE
Can't create a community

### ISSUE THREAD

**Issue by weex** [OpenHospitalityNetwork/ohn-solid#6] opened 2021-12-14 05:46 UTC
I see offers and can create them but I also see communities and have no way to create communities.

**Comment by mrkvon** [comment] 2022-08-27 18:46
#16 is a duplicate of this. However, we started a discussion there. So, although this issue has precedence, i'll close it in favor of #16, and we can keep the discussion going there. ❤️ 

I hope that's ok @weex

**Closed as completed by mrkvon** 2022-08-27 18:46 UTC
